import React, { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import api from "../services/api";
import { startSpeakingSession, sendSpeakingMessage, getSessionMessages, endSpeakingSession } from "../services/speakingService";
import { getStoredUser } from "../services/authService";

const LIMITS = { Basic: 2 * 3600, Premium: 5 * 3600, Advance: 10 * 3600 };
const formatTime = (seconds) => { const s=Math.max(0,Math.floor(seconds)); const h=Math.floor(s/3600); const m=Math.floor((s%3600)/60); const sec=s%60; return h ? `${h}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}` : `${m}:${String(sec).padStart(2,"0")}`; };

export default function AIChat() {
  const [params] = useSearchParams(); const navigate=useNavigate(); const user=getStoredUser();
  const friend=params.get("friend")||"AI Friend", topic=params.get("topic")||"General English", story=params.get("story")||"", language=params.get("language")||"auto";
  const [sessionId,setSessionId]=useState(null), [usageSessionId,setUsageSessionId]=useState(null), [usage,setUsage]=useState({usedSeconds:0,limitSeconds:LIMITS[user?.plan||"Basic"]});
  const [messages,setMessages]=useState([]), [input,setInput]=useState(""), [typing,setTyping]=useState(false), [loading,setLoading]=useState(true); const bottomRef=useRef(null);
  const remaining=Math.max(0,usage.limitSeconds-usage.usedSeconds);

  const startUsage=async()=>{ const r=await api.post("/ai-usage/start"); setUsageSessionId(r.data.sessionId); setUsage({usedSeconds:r.data.usedSeconds,limitSeconds:r.data.limitSeconds}); return r.data.sessionId; };
  useEffect(()=>{ let mounted=true; (async()=>{ try { await startUsage(); const data=await startSpeakingSession({friendName:friend,topic,story,preferredLanguage:language,personality:"supportive personal language-learning friend",level:"intermediate",voice:"female",mode:"chat"}); const id=data.session?.id; if(!mounted)return; setSessionId(id); const history=await getSessionMessages(id); setMessages((history.messages||[]).map(m=>({...m,text:m.content}))); } catch(e){ alert(e.response?.data?.message||"Unable to start AI chat."); navigate("/speaking-practice"); } finally { if(mounted)setLoading(false); } })(); return()=>{mounted=false;}; },[]);
  useEffect(()=>{ if(!usageSessionId)return; const hb=async()=>{try{const r=await api.post("/ai-usage/heartbeat",{sessionId:usageSessionId});setUsage(p=>({...p,usedSeconds:r.data.usedSeconds,limitSeconds:r.data.limitSeconds}));if(r.data.limitReached)endChat(true);}catch{}}; hb(); const id=setInterval(hb,10000); return()=>clearInterval(id); },[usageSessionId]);
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"});},[messages]);
  const endChat=async(limit=false)=>{ if(sessionId)await endSpeakingSession(sessionId).catch(()=>{}); if(usageSessionId)await api.post("/ai-usage/stop",{sessionId:usageSessionId}).catch(()=>{}); setUsageSessionId(null); if(limit)alert("Your daily AI time is finished for today."); navigate("/speaking-practice"); };
  const send=async(e)=>{e.preventDefault();if(!input.trim()||!sessionId||typing||remaining<=0)return;const text=input.trim();setInput("");setMessages(p=>[...p,{role:"user",text}]);setTyping(true);try{const r=await sendSpeakingMessage({sessionId,message:text});const reply=r.assistantMessage?.content||"Tell me more.";setMessages(p=>[...p,{role:"assistant",text:reply}]);}catch(e){if(e.response?.status===429)alert("Your daily AI time has been reached.");}finally{setTyping(false);}};
  if(loading)return <div className="min-h-screen flex items-center justify-center bg-[#F8FAF9]"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-slate-200 border-t-black"/><p className="mt-4 text-sm text-slate-500">Preparing your AI friend…</p></div></div>;
  return <div className="min-h-screen bg-[#F8FAF9] text-slate-900"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4"><Link to="/speaking-practice" className="font-bold">← Speaking Practice</Link><div className="text-right"><p className="font-bold">{friend}</p><p className="text-xs text-slate-400">AI Chat · {user?.plan||"Basic"}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold">AI {formatTime(remaining)} left</span><button onClick={()=>endChat()} className="rounded-xl bg-black px-4 py-2 text-xs font-bold text-white">End</button></div></header><main className="mx-auto grid min-h-[calc(100vh-73px)] max-w-6xl gap-6 p-5 lg:grid-cols-[1fr_330px]"><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="mb-5 rounded-2xl bg-slate-50 p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">YOUR SCENARIO</p><p className="mt-2 font-semibold">{topic}</p>{story&&<p className="mt-2 text-sm leading-6 text-slate-500">{story}</p>}<p className="mt-3 text-xs font-bold text-[#477D65]">Language: {language}</p></div><div className="space-y-4">{messages.map((m,i)=><div key={i} className={m.role==="user"?"ml-8":"mr-8"}><div className={`rounded-2xl p-4 text-sm leading-6 ${m.role==="user"?"bg-black text-white":"bg-slate-50 text-slate-700"}`}><p className="mb-1 text-[10px] font-bold uppercase tracking-wider opacity-50">{m.role==="user"?"You":friend}</p>{m.text}</div></div>)}{typing&&<div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-400">AI is thinking…</div>}<div ref={bottomRef}/></div><form onSubmit={send} className="mt-6 flex gap-2 border-t border-slate-100 pt-5"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about your story, a word, grammar, or what to say next…" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-black"/><button disabled={!input.trim()||typing||remaining<=0} className="rounded-xl bg-black px-5 py-3 text-sm font-bold text-white disabled:opacity-30">Send</button></form></section><aside className="h-fit rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-bold">What your AI friend can do</h2><ul className="mt-4 space-y-3 text-sm text-slate-500"><li>• Understand your own story and scenario.</li><li>• Answer follow-up questions related to it.</li><li>• Explain English words and grammar.</li><li>• Reply in Hindi/Hinglish when selected.</li><li>• Add new vocabulary from your story and messages to Speakly's word bank.</li><li>• Stay available for your plan's daily AI time.</li></ul></aside></main></div>;
}
