import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { createAssignment } from "../services/assignmentService";

export default function CreateAssignment() {
  const navigate = useNavigate(); const [form, setForm] = useState({ title: "", description: "", dueDate: "" }); const [message, setMessage] = useState("");
  const submit = async (e) => { e.preventDefault(); try { await createAssignment(form); setMessage("Assignment created and sent to your connected students."); setTimeout(() => navigate("/assignments"), 700); } catch (error) { setMessage(error.response?.data?.message || "Could not create assignment."); } };
  return <div className="min-h-screen bg-[#F8FAF9] px-6 py-12"><div className="mx-auto max-w-2xl"><p className="text-sm font-bold text-[#65B891]">TEACHER</p><h1 className="mt-3 text-4xl font-extrabold">Create assignment</h1><p className="mt-3 text-slate-500">Your connected Premium/Advance students will see the work in Teacher's Lessons.</p><form onSubmit={submit} className="mt-10 rounded-3xl bg-white p-8"><label className="text-sm font-bold">Assignment title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Everyday Conversations" className="mt-3 w-full rounded-xl border border-slate-200 px-5 py-4 outline-none focus:border-black"/></label><label className="mt-5 block text-sm font-bold">Instructions<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={5} placeholder="Use this week's vocabulary in five natural sentences…" className="mt-3 w-full rounded-xl border border-slate-200 px-5 py-4 outline-none focus:border-black"/></label><label className="mt-5 block text-sm font-bold">Due date<input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} className="mt-3 w-full rounded-xl border border-slate-200 px-5 py-4 outline-none focus:border-black"/></label>{message && <p className="mt-4 text-sm font-semibold text-slate-500">{message}</p>}<button type="submit" className="mt-6 rounded-xl bg-black px-6 py-4 font-bold text-white">Create assignment →</button></form></div></div>;
}
