import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { createCheckoutSession } from "../services/paymentService";

const plans = [
  { name: "Basic", price: "Free", features: ["2 new words each day", "1 sentence + 1 phrase + 1 modal each day", "Daily AI challenge", "Weekly AI challenge", "AI practice up to 2 hours/day", "Revision from your own history", "No teacher-assigned work", "No contests"], color: "border-slate-200", btnClass: "bg-slate-100 text-slate-900 hover:bg-slate-200" },
  { name: "Premium", price: "₹199", features: ["3 new words each day", "Daily sentence, phrase and modal practice", "Daily + weekly AI challenges", "AI practice up to 5 hours/day", "Teacher connection + teacher lessons", "Teacher assignments and feedback", "Contest access", "Detailed AI feedback"], color: "border-slate-600 ring-2 ring-slate-600", btnClass: "bg-slate-600 text-white hover:bg-slate-700", popular: true },
  { name: "Advance", price: "₹399", features: ["5 new words each day", "Everything in Premium", "AI practice up to 10 hours/day", "Advanced personalized learning", "Teacher work + advanced feedback", "Contest access", "Advanced speaking and accent practice", "Priority support"], color: "border-slate-200", btnClass: "bg-slate-900 text-white hover:bg-black" }
];

export default function Pricing() {
  const navigate = useNavigate(); const [loading, setLoading] = useState("");
  const choose = async (name) => { if (name === "Basic") return navigate("/student"); setLoading(name); try { const data = await createCheckoutSession(name); if (data.url) window.location.href = data.url; } catch (e) { alert(e.response?.data?.message || "Something went wrong with payment."); } finally { setLoading(""); } };
  return <div id="pricing" className="min-h-screen bg-[#F8FAF9] px-6 py-20"><div className="mx-auto max-w-6xl text-center"><p className="text-sm font-bold uppercase tracking-[0.2em] text-slate-600">Pricing Plans</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Choose the amount of help you need.</h1><p className="mx-auto mt-4 max-w-2xl text-lg text-slate-600">The plan controls access to teacher work, contests and daily AI time. Your daily learning class remains personalized on every plan.</p><div className="mt-16 grid gap-8 md:grid-cols-3">{plans.map((plan) => <div key={plan.name} className={`relative flex flex-col rounded-3xl border bg-white p-8 shadow-sm ${plan.color}`}>{plan.popular && <span className="absolute -top-4 left-1/2 -translate-x-1/2 rounded-full bg-slate-600 px-3 py-1 text-xs font-bold text-white">MOST POPULAR</span>}<h3 className="text-2xl font-bold">{plan.name}</h3><div className="mt-4"><span className="text-4xl font-extrabold">{plan.price}</span>{plan.price !== "Free" && <span className="text-sm text-slate-500">/month</span>}</div><ul className="mt-8 flex-1 space-y-4 text-left">{plan.features.map((feature) => <li key={feature} className="flex gap-3 text-sm text-slate-600"><span>✓</span>{feature}</li>)}</ul><button disabled={!!loading} onClick={() => choose(plan.name)} className={`mt-10 w-full rounded-2xl py-4 font-bold ${plan.btnClass}`}>{loading === plan.name ? "Processing…" : plan.name === "Basic" ? "Current free plan" : `Choose ${plan.name}`}</button></div>)}</div></div></div>;
}
