import React from "react";
import { Link } from "react-router-dom";
import { getStoredUser } from "../services/authService";

export default function SpeakingPractice() {
  const user = getStoredUser();
  const plan = user?.plan || "Basic";
  const videoAllowed = plan !== "Basic" || import.meta.env.VITE_DEVELOPER_MODE === "true";
  return <div className="min-h-screen bg-[#F8FAF9] p-6 sm:p-10"><div className="mx-auto max-w-5xl"><Link to="/student" className="text-sm font-bold text-slate-500">← Dashboard</Link><div className="mt-12 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#65B891]">SPEAKING PRACTICE</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Practice English your way.</h1><p className="mx-auto mt-4 max-w-2xl text-slate-500">Give the AI your own story or scenario, ask questions about it, and keep the conversation focused on what you actually need to say.</p></div><div className="mx-auto mt-10 grid max-w-4xl gap-6 md:grid-cols-2"><Link to="/ai-friend?mode=chat" className="block rounded-[2rem] bg-black p-9 text-white transition hover:-translate-y-1 hover:shadow-2xl"><span className="text-5xl">💬</span><h2 className="mt-6 text-3xl font-bold">AI Chat</h2><p className="mt-3 text-sm leading-7 text-neutral-300">All plans can chat with an AI friend. Give your story, ask queries, get Hindi/Hinglish support, and learn vocabulary from your scenario.</p><span className="mt-7 inline-block font-bold">Create your AI friend →</span></Link>{videoAllowed ? <Link to="/ai-friend?mode=video" className="block rounded-[2rem] border border-slate-200 bg-white p-9 transition hover:-translate-y-1 hover:shadow-xl"><span className="text-5xl">🤖</span><h2 className="mt-6 text-3xl font-bold">AI Video Call</h2><p className="mt-3 text-sm leading-7 text-slate-500">Premium and Advance can also talk face-to-face with a male or female animated AI assistant.</p><span className="mt-7 inline-block font-bold text-slate-900">Start video AI →</span></Link> : <div className="relative rounded-[2rem] border border-slate-200 bg-white p-9"><div className="absolute right-6 top-6 rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500">🔒 Premium+</div><span className="text-5xl grayscale">🤖</span><h2 className="mt-6 text-3xl font-bold">AI Video Call</h2><p className="mt-3 text-sm leading-7 text-slate-500">Basic keeps the full AI chat experience. Upgrade to Premium or Advance for animated AI video calls.</p><Link to="/pricing" className="mt-7 inline-block font-bold text-slate-900">View plans →</Link></div>}</div><div className="mx-auto mt-8 max-w-4xl rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-500"><strong className="text-slate-800">Student Video Room is in Community.</strong> It is only for accepted friends and private invitations; it is separate from the AI video call.</div></div></div>;
}
